### ISSUE TITLE
Converting "variable scope" blocks.

### ISSUE THREAD

**Issue by DualBrain** [paul1956/CSharpToVB#51] opened 2020-12-10 21:05 UTC
It is relatively common to encounter C# code where variable scoping blocks are in use.

I recently encountered such when working on converting tests for the VB runtime:

        [Fact]
        public void Close()
        {
            var path = GetTestFilePath();
            File.WriteAllText(path, "abc123");
            // ...
            using (var parser = new TextFieldParser(path))
            {
                parser.Close();
            }
           // ...
            {
                TextFieldParser parser;
                using (parser = new TextFieldParser(path))
                {
                }
                parser.Close();
            }
        }

As you can see in the second block, the local parser variable is used "again" - but it's a new/different parser variable.

The simplest way to do something similar in VB (which I do rather regularly - unrelated to converting code) is to:

    If True Then
        ' We now have a separate variable scope.
    End If

So the question is can you detect these types of block and replace them with the If True Then ... End If blocks?

**Comment by paul1956** [comment] 2020-12-11 00:57
@DualBrain I can't detect that, the problem is the second using should just be "Using parser as new TextFieldParser(path))" and that I might be able to fix.

**Comment by paul1956** [comment] 2020-12-11 02:02
I fix the specific issue and other places where I should have used
```
Dim X As New Y
```
Fix in   New in 5.0.0.17/5.0.0.8

**Comment by DualBrain** [comment] 2020-12-11 02:27
You might have misunderstood what I was trying to convey.

    public void SomeSuch()
    {

        {
            int x = 1;
        }
        // ...
        {
            int x = 1;
        }
    }

There are two different instances of x in their own individual variable scopes due to the curly brace "blocks".  In VB this can be done using:

    Public Sub SomeSuch

        If True Then
            Dim x = 1
        End If
        If True Then
            Dim x = 1
        End If

     End Sub

The question I was asking was related to the curly brace sections so that they could be detected (if possible) and turned into the "do nothing" (except create variable scoping) If / End If blocks.

**Comment by DualBrain** [comment] 2020-12-11 02:34
Also, right now... if I attempt to convert this:

    Public Sub SomeSuch()
        Dim x As Integer = 1
        ' ...
         Dim x As Integer = 1
        ' ...
    End Sub

Which is obviously not a valid conversion. ;-)

**Comment by paul1956** [comment] 2020-12-13 00:52
@DualBrain Fixed in 5.0.0.18/5.0.0.10, please review

**Closed as completed by paul1956** 2020-12-13 00:52 UTC

**Comment by DualBrain** [comment] 2020-12-14 21:43
Excellent work!

**Comment by paul1956** [comment] 2020-12-15 01:54
@DualBrain  thanks. Very odd the original code had a test identical to your your simplified example. Which I had to fix for some reason whoever wrote original code that it was OK to define a variable twice.
