### ISSUE TITLE
Small things to Fix

### ISSUE THREAD

**Issue by VBAndCs** [paul1956/CSharpToVB#19] opened 2020-03-22 01:17 UTC
Well done @
This is a very good converter, but I have some notes:

1. I tried to convert a solution, but get a MsgBox saying something about Nugets. So I converted the folder instead.

2. When converting the `Namespace statement`, try to exclude the root namespace, because it is the default namespace in VB
in C#:
`Namespace Microsoft.eShopWeb.Infrastructure.Data`
in VB:
`Namespace Data`

The project name is `Infrastructure` and the default namespace is `Microsoft.eShopWeb.Infrastructure`
This info stored in the .csprog file. Try to consider parsing it when converting a folder that contains it.

3. A common error I face in converters, is to inherit an interface:
```
    Public Class CatalogTypeConfiguration
        Inherits IEntityTypeConfiguration(Of CatalogType)
```

If the name doesn't start with I , inherit, otherwise, search all files in the directly for `class IEntityTypeConfiguration` or `interface IEntityTypeConfiguration` to take an accurate decision. inheriting an interface means that all methods will miss the `Implements` part, and this needs a long manual correction.

4. `AddressOf` is added for lamdas:
Input:
`_items.RemoveAll(i => i.Quantity == 0);`
Output:
`_items.RemoveAll(AddressOf Function(i) i.Quantity = 0)`

5. you renamed a property `BuyerId` to ` BuyerId_Renamed`  because there is a param in the constructor with the same name but small cased `buyerId`. This caused errors in other files calling this property.
It is not a problem in VB to have a param and a property with the same name. You just add `Me.` before the name of the property in the assignment:
`Me.BuyerId= buyerId`

Hope you fix these, to have a perfect converter.
Thanks again. It is really useful.

**Comment by paul1956** [comment] 2020-03-22 02:01
@VBAndCs this would be better split into 1 issue per otherwise it is hard to address.
1. There is no convert solution, if you mean project then yes something broke recently #17 and I should just disable it until the underlying issue is fixed in MSBuild.
2. When I do folders I don't look at project files, so this would be hard to do.
3. I only look at 1 file at a time when I convert folders, for projects this should convert correctly or I have a bug which I can't look at until the project conversion issue #17 is fixed.
4. Was a bug #16  I fixed another case I missed but I may not be yours. If you can still reproduce with today's build please post a repo.
5. I thought I fixed this last week for most cases, if the current version still does in can you post a small repo, it should be an easy fix.

**Comment by VBAndCs** [comment] 2020-03-22 03:23
Test on this:
https://github.com/dotnet-architecture/eShopOnWeb

**Comment by VBAndCs** [comment] 2020-03-22 04:28
Related to 5:
In some constructors, you used another approach by adding `_` in as a prefix to the param like `_catalogItemId`. This broke the conventions of EF binding and caused exceptions took me sometime to understand.
So, as a rule: DON'T CHANGE ANY NAME unless there is no other way.

**Comment by paul1956** [comment] 2020-03-22 05:05
Issue 5 above is fixed is today's build. Let me know if you have another repo.

**Comment by paul1956** [comment] 2020-03-22 10:57
@VBAndCs it has to do with the way things are parsed, the app builds a symbol table and needs to deal with mixed case. The app only walks the tree once, the internal symbol table is case sensitive built top down, mostly left to right with special cases where I have found issues. I will try your repo.

**Comment by paul1956** [comment] 2020-03-28 00:32
@VBAndCs  I believe with Convert Project all of these are now fixed they will now be fixed completely for Convert folders, https://github.com/dotnet-architecture/eShopOnWeb now converts if you do it by project. If you still have any issue please prove a complete example (at least a C# file) that shows the issue I can do very little with below since I don't know what Items are.
```
_items.RemoveAll(i => i.Quantity == 0);
```

**Closed as completed by paul1956** 2020-03-28 00:32 UTC
