### ISSUE TITLE
 Could not load file or assembly NuGet.Versioning

### ISSUE THREAD

**Issue by jnm2** [paul1956/CSharpToVB#9] opened 2020-03-14 01:18 UTC
The program shows this error message for all the csprojs that I've tried so far. Example:

https://github.com/Techsola/AmbientTasks/blob/d5a686e8dae0c578b7fe5487a5302d2dd52fd340/src/AmbientTasks/AmbientTasks.csproj

> Msbuild failed when processing the file 'C:\Users\Joseph\Source\Repos\AmbientTasks\src\AmbientTasks\AmbientTasks.csproj' with message:Msbuild failed when processing the file 'C:\Users\Joseph C:\Program Files\dotnet\sdk\3.1.200-preview-015002\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets: (160, 5): The "GetAssemblyVersion" task failed unexpectedly.
> System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Versioning, Version=5.5.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
> File name: 'NuGet.Versioning, Version=5.5.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
>    at Microsoft.NET.Build.Tasks.GetAssemblyVersion.ExecuteCore()
>    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

**Comment by paul1956** [comment] 2020-03-14 09:00
Note sure what the issue is, it might have something to do with MSLocator

**Comment by paul1956** [comment] 2020-03-15 12:08
This may be the same as #19, with more details so I will not close

**Comment by paul1956** [comment] 2020-03-27 17:31
Fixed in 4.2.0.0

**Closed as completed by paul1956** 2020-03-27 17:31 UTC
Labels: duplicate
